spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: '{cipher}AQA5h4dQdDNQZuJA+ukAKwus74HwXiHMK+DM+CKTSdxNp2kzy9ktGyJFBH2IqcbuVS2aLb9XjsYES6/Tz5vkh6kGHwnBW0ivIy4okcpksKZPPLJf0CyMXcfqZ09/4zNyLvsRjpzlhMiIADEHrLOUiMwlcEgTaZhC54PnpQF66b9ru874LgOyR6MjMf0+1W/FJhKTSJrTyxbwoMsyff2XfL7ss1GoDNRyu3Hjx3D38uhH+cCrnW1/ZfsH2vUzUOoieZvbyEI7ko/8Ic37hWon09x7UAVPToLJzLfsb+d1MkRRn1gVRp94NRMw3PWVGgtcBZ2tgbOT+Bv35QVJaptqJdHISeOYdaOOXkfCZthpV428UAZTlCO/pPC9hw5lY5yzhrw='
    generate-unique-name: false

token:
  #secret: user_token_default
  secret: '{cipher}AQALwxvK+NXpOyP9aJTbw0nXbmu/zNtvvqeRQLW0x3L67vnTrvd24ZSS7wywt/vkmy7RTJl2+cwEokNTPDBGG24cUP5jGinXTAQsG/JtElXL9h5+KKG4vAn62QfPVjq2LHVbm7qGkBGuGwOJ9o5eXeu4Gt1C2+ygd8QqsjNWDrEc1wVAZSsvXzxhuwvCM8UL4JSGbReE/uRYfv2pxcDeE3H1SF9D0+NAHnGlakGUBKq1neP41q/PWEZtDAbZRVWiwhQV8JZuFQ1GoDVyGMTBQvIdljxCPl0ii8dhhAZhjM0uAx3vt6BxR7h9ap5lDcULAYa+UVw4+7Tme5iahNkYfuliompxOkc8UVOoe2937YJVdZVcpJqrK9KhtoLzH514SOU='
  expiration_time: 86400000

gateway:
  ip: 192.168.25.28

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty:  User's orders is empty!

#깃 커밋 : 해당경로 이동 > git add . > git commit -m "comment"
#push : git remote -v 확인 후 
#git push --set-upstream origin master 연결
#git push --set-upstream origin master 최초 푸쉬일경우
        
        